# Keep trackers active while connected. Enter WOM only when the receiver has
# been unavailable for the connection timeout duration.
CONFIG_USE_IMU_WAKE_UP=y
CONFIG_CONNECTION_TIMEOUT_USE_WOM=y
CONFIG_USE_ACTIVE_TIMEOUT=n
CONFIG_USE_IMU_TIMEOUT=n
CONFIG_SENSOR_USE_LOW_POWER_2=n
CONFIG_CONNECTION_TIMEOUT_DELAY=30000
