CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_SENSOR=y

CONFIG_SLIMEVR_USB_DEVICE_MANUFACTURER="Seeed Studio"
CONFIG_SLIMEVR_USB_DEVICE_PRODUCT="SlimeNRF Tracker XIAO nRF54LM20A"
CONFIG_BATTERY_USE_REG_LDO_MAPPING=y
CONFIG_LED_RGB_COLOR=y
